language: python

python:
  - "3.6"

notifications:
    email:
      recipients:
        - hectorabrahammp@gmail.com
      on_success: never
      on_failure: always

install:
  - pip install --upgrade pip
  - pip install pycodestyle
  - pip install -r requirements.txt

script:
  # List the PEP8 error - We should fix their
  - find . -name \*.py -exec pycodestyle --ignore=E402,W504,W605 {} +

  - cd test
  - python -m unittest discover -v