language: python

python:
  - "3.6"

notifications:
    email:
      recipients:
        - hectorabrahammp@gmail.com
      on_success: never
      on_failure: always

install:
  - pip install -r requirements.txt

script:
  - cd test
  - python -m unittest discover -v